-- Count rows in each table
SELECT COUNT(*) AS team_count FROM TEAMS;
SELECT COUNT(*) AS tournament_count FROM TOURNAMENTS;
SELECT COUNT(*) AS location_count FROM LOCATIONS;
SELECT COUNT(*) AS match_count FROM MATCHES;
SELECT COUNT(*) AS stat_count FROM MATCH_STATISTICS;

-- Display all data from each table
SELECT * FROM TEAMS LIMIT 10;
SELECT * FROM TOURNAMENTS LIMIT 10;
SELECT * FROM LOCATIONS LIMIT 10;
SELECT * FROM MATCHES LIMIT 10;
SELECT * FROM MATCH_STATISTICS LIMIT 10;

